name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - colcon-common-extensions
  - rosinstall_generator
  - vcstool
  - asio
  - tinyxml2
  - tinyxml
  - openssl
  - eigen
  - log4cxx
